### ISSUE TITLE
REQMOD

### ISSUE THREAD

**Issue by ofilin86** [allangood/icap_server#1]
Hi,
Modules not working in method REQMOD
Help

**Comment by allangood** [comment]
Hello Oleg,

This iCap server is very experimental and doesn't work in a stable way...
The code is there to receive help to be honest.
Sorry, but at this stage the server is not usable.
But I will work on code to improve it and reach the alpha stage.

Regards.

**Comment by ofilin86** [comment]
Ok, thanks for your work
