### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ofilin86** [allangood/icap_server#2]
Windows OS not have uid

```
Traceback (most recent call last):
  File "icap_server_orig.py", line 272, in <module>
    if (os.getuid() == 0):
AttributeError: 'module' object has no attribute 'getuid'
```

in icap_server.py
```
if not sys.platform == 'win32':
        if (os.getuid() == 0):
            drop_rivileges(run_as_user,run_as_group)
```

**Comment by allangood** [comment]
Yes, and due to this the line " if not sys.platform == 'win32' " is there, just before the os.getuid.
But I think you are executing inside cygwin, correct?

I will change this.

Thank you!
